# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f <- function(x, w) {
    .Call(RGLFM_f, x, w)
}

rcpp_hello_world <- function() {
    .Call(RGLFM_rcpp_hello_world)
}

[[Rcpp::depends <- function(N_, D_, K_, maxK_, missing_, X, Z, C_, B, theta, R_, f_, mu_, w_, s2y_, bias_, alpha_, s2B_, s2u_, Nsim_) {
    .Call(RGLFM_[[Rcpp::depends, N_, D_, K_, maxK_, missing_, X, Z, C_, B, theta, R_, f_, mu_, w_, s2y_, bias_, alpha_, s2B_, s2u_, Nsim_)
}

