# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IBPsampler <- function(input_X, input_C, input_Z, input_bias, input_F, input_s2u, input_s2B, input_alpha, input_Nsim, input_maxK, input_missing) {
    .Call('RcppGSLExample_IBPsampler', PACKAGE = 'RcppGSLExample', input_X, input_C, input_Z, input_bias, input_F, input_s2u, input_s2B, input_alpha, input_Nsim, input_maxK, input_missing)
}

