# Use an official Python runtime as a parent image
FROM ubuntu:xenial

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

# Install Git and other basic modules
RUN apt-get update && \
    apt-get -y --no-install-recommends install \
    ca-certificates \
    git \
    wget \
    bzip2 \
    vim \
    build-essential

RUN apt-get -y install r-base

RUN useradd -m -s /bin/bash cranR
USER cranR

# Set the working directory
WORKDIR /home/cranR

USER root
RUN apt-get -y install libgsl0-dev

#RUN apt-get -y install libcurl4-openssl-dev
#setup R configs
RUN echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > ~/.Rprofile

# Installing R packages
RUN Rscript -e 'install.packages("Rcpp")'
RUN Rscript -e 'install.packages("RcppGSL")'
RUN Rscript -e 'install.packages("matrixStats")'
RUN Rscript -e 'install.packages("ggplot2")'
RUN Rscript -e 'install.packages("R.matlab")'

# Downloading GLFM package
RUN git clone https://github.com/ivaleraM/GLFM.git

# Compiling GLFM package
RUN R CMD build GLFM/src/Ccode/wrapper_R/RcppGSLExample
RUN R CMD INSTALL GLFM/src/Ccode/wrapper_R/RcppGSLExample
#R CMD check GLFM/src/Ccode/wrapper_R/RcppGSLExample

