# Use an official Python runtime as a parent image
FROM ubuntu:xenial

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

# Install Git and other basic modules
RUN apt-get update && \
    apt-get -y --no-install-recommends install \
    ca-certificates \
    git \
    wget \
    bzip2 \
    vim \
    build-essential

RUN apt-get -y install r-base

# RUN apt-get -y install python-qt4

RUN useradd -m -s /bin/bash cranR
USER cranR

# Set the working directory
WORKDIR /home/cranR

# executable part

RUN git clone https://github.com/ivaleraM/GLFM.git

USER root
RUN apt-get -y install libgsl0-dev

#RUN apt-get -y install libcurl4-openssl-dev
#setup R configs
RUN echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > ~/.Rprofile

RUN Rscript -e "setwd('GLFM/src/Ccode')"
RUN Rscript -e 'install.packages("Rcpp")'
RUN Rscript -e 'require("Rcpp")'
RUN Rscript -e 'install.packages("GLFM/src/Ccode/wrapper_R", repos = NULL, type="source")'
#RUN Rscript -e 'compileAttributes("GLFM/src/Ccode/wrapper_R",verbose=TRUE)'
RUN Rscript -e 'setwd("GLFM/src/GLFMR")'

USER cranR
