// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// IBPsampler
Rcpp::List IBPsampler(const RcppGSL::Matrix input_X, Rcpp::CharacterVector input_C, RcppGSL::Matrix& input_Z, SEXP input_bias, Rcpp::NumericVector input_F, SEXP input_s2u, SEXP input_s2B, SEXP input_alpha, SEXP input_Nsim, SEXP input_maxK, SEXP input_missing);
RcppExport SEXP RcppGSLExample_IBPsampler(SEXP input_XSEXP, SEXP input_CSEXP, SEXP input_ZSEXP, SEXP input_biasSEXP, SEXP input_FSEXP, SEXP input_s2uSEXP, SEXP input_s2BSEXP, SEXP input_alphaSEXP, SEXP input_NsimSEXP, SEXP input_maxKSEXP, SEXP input_missingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const RcppGSL::Matrix >::type input_X(input_XSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type input_C(input_CSEXP);
    Rcpp::traits::input_parameter< RcppGSL::Matrix& >::type input_Z(input_ZSEXP);
    Rcpp::traits::input_parameter< SEXP >::type input_bias(input_biasSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type input_F(input_FSEXP);
    Rcpp::traits::input_parameter< SEXP >::type input_s2u(input_s2uSEXP);
    Rcpp::traits::input_parameter< SEXP >::type input_s2B(input_s2BSEXP);
    Rcpp::traits::input_parameter< SEXP >::type input_alpha(input_alphaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type input_Nsim(input_NsimSEXP);
    Rcpp::traits::input_parameter< SEXP >::type input_maxK(input_maxKSEXP);
    Rcpp::traits::input_parameter< SEXP >::type input_missing(input_missingSEXP);
    rcpp_result_gen = Rcpp::wrap(IBPsampler(input_X, input_C, input_Z, input_bias, input_F, input_s2u, input_s2B, input_alpha, input_Nsim, input_maxK, input_missing));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP colNorm_old(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"RcppGSLExample_IBPsampler", (DL_FUNC) &RcppGSLExample_IBPsampler, 11},
    {"colNorm_old",               (DL_FUNC) &colNorm_old,                2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppGSLExample(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
