%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/melanie/Documents/UC3M/Workspace/GIBP_Isabel/simulations/data/pbc.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/12/21 09:19:50

%% Initialize variables.
filename = '/home/melanie/Documents/UC3M/Workspace/GIBP_Isabel/simulations/data/pbc.csv';
delimiter = ';';
startRow = 2;

%% Format string for each line of text:
%   column5: text (%s)
%	column8: text (%s)
%   column9: text (%s)
%	column10: text (%s)
%   column16: text (%s)
%	column18: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%*s%*s%s%*s%*s%s%s%s%*s%*s%*s%*s%*s%s%*s%s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
sex = dataArray{:, 1};
spiders = dataArray{:, 2};
hepatom = dataArray{:, 3};
ascites = dataArray{:, 4};
drug = dataArray{:, 5};
edema = dataArray{:, 6};

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;